apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSnRJZzBXdklGdEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBek1UVXdOakUwTURCYUZ3MHpOREF6TVRNd05qRTVNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPSkRPaU1ja0VpbmQ1SFRpWVdHdTk2cFZqOXJweXgxV0tVekhXaVMxbWtuU1FDSUJIZ2dmb0Z0WVEKcUJldUljbWFsYUxnRFliaEtzUWdtVW95TGE0SlptMk96QWxVSnNiK1dyR2FnOFVEcG9HcWcxdGRKYk9HTmNlSwpOZnQydTQ0cjlZWHdBbDVxdTlnMkVjc0RhbktmSHFZSGk1SUphK0YvUHNBa2FlRHowTUVZTkFBSmFyMDcrQ0hLCmYvVlRPMDVNOXhRRDc5c0l4V294K3BEaC81ei9MV2JpMktYQ2pzYkVYOWhjZWR4Q1dJOUo0bHpocnloak9udHoKbTJ0RTVka1hzSzFFTVdkaFkxWjRuTzR6TmF0azJrQkh0Q21FTFNmdXE4T0lNb3dyd0NES0FjTkF6K0dKZ0RhUwp0azB5eElQbEo2RVNDTHJyVXpxeWhCaElibms3QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUTGlBdXRDY0s5cXAyMTBkWUd5aS9aeDFYQVlqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnF0aDJFdENpaQpZQ3FTRG1UVDdzUVFoYThhZFBmaEMzVWVSTWQ1TEtzY3drQ1E4WElNbmRxS044dzNtdXdpQWtES3grQjV0VDJaClhBNlp1cXFjQkh1K2NHSzBqTU0rVlYxRFYvMkY0QUVNSnNWZjJQazkvVkNWckpYa0Rxa2hTeGplbVp2NnZKTSsKRjlLV2EycWdaY0VVT2MrNXJXcW9xUnZwUGx3NVd6MHoxcGJUakJ3c2pUenY1MzVWOVlyTUxHMXFWd2ZsaFlpQgo3aXZkWmhaV1JEUFl5emg2Rzdqb2xMUndKMHYxcEtpVEJvOWNSYk9yNEpoaHlYbDhYMU9HeFBiQXF5N21nSGp4CjNuQ0JsMTdKa1h6L0YzL20zdC9WWFMrcW5UcThIMjNzWW43UithODBjVUhrZFMyUGExaVBLeHNYMlJyVTNiclEKaG5BUXJMNzBmS21DCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://E80190EAC6739FF99557DAA260BB073E.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:324005994172:cluster/cbcd-bp02-swen-demo-eks
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:324005994172:cluster/cbcd-bp02-swen-demo-eks
    user: arn:aws:eks:us-east-1:324005994172:cluster/cbcd-bp02-swen-demo-eks
  name: arn:aws:eks:us-east-1:324005994172:cluster/cbcd-bp02-swen-demo-eks
current-context: arn:aws:eks:us-east-1:324005994172:cluster/cbcd-bp02-swen-demo-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:324005994172:cluster/cbcd-bp02-swen-demo-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - cbcd-bp02-swen-demo-eks
      - --output
      - json
      command: aws
